spring:
  profiles:
    active: dev,female
  datasource:
    url: jdbc:mysql://192.168.199.128:3306/mp
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.56.101
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: ''
    port: 6379
    timeout: 5000

server:
  port: 8083
  compression:
    enabled: true
logging:
  file:
    path: E:/java/demo/log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:xml/*Mapper.xml





